trigger EmployeeTrigger on Employee__c (after insert,after delete, after undelete) {
    if(Trigger.isDelete){
        if(Trigger.isAfter){
            EmployeeTriggerHandler.Q29(Trigger.old);
            EmployeeTriggerHandler.Q32(Trigger.old);
        }
    }
    if(Trigger.isUndelete){
        if(Trigger.isAfter){
            EmployeeTriggerHandler.Q31(Trigger.New);
            EmployeeTriggerHandler.Q32(Trigger.New);
        }
    }
    if(Trigger.isInsert){
        if(Trigger.isAfter){
            EmployeeTriggerHandler.Q32(Trigger.New);
        }
    }
}